In [2]:
import pandas as pd
import numpy as np

In [3]:
ppl=pd.read_csv('people.csv')
act=pd.read_csv('act_train.csv')

In [4]:
ppl['date']=ppl['date'].apply(lambda x: pd.to_datetime(x,format="%Y-%m-%d") )
act['date']=act['date'].apply(lambda x: pd.to_datetime(x,format="%Y-%m-%d") )

In [11]:
act2=pd.merge(act,ppl,how='left',left_index=True,on='people_id',suffixes=('_act','_ppl'))
act2.columns

Index([u'people_id', u'activity_id', u'date_act', u'activity_category',
       u'char_1_act', u'char_2_act', u'char_3_act', u'char_4_act',
       u'char_5_act', u'char_6_act', u'char_7_act', u'char_8_act',
       u'char_9_act', u'char_10_act', u'outcome', u'char_1_ppl', u'group_1',
       u'char_2_ppl', u'date_ppl', u'char_3_ppl', u'char_4_ppl', u'char_5_ppl',
       u'char_6_ppl', u'char_7_ppl', u'char_8_ppl', u'char_9_ppl',
       u'char_10_ppl', u'char_11', u'char_12', u'char_13', u'char_14',
       u'char_15', u'char_16', u'char_17', u'char_18', u'char_19', u'char_20',
       u'char_21', u'char_22', u'char_23', u'char_24', u'char_25', u'char_26',
       u'char_27', u'char_28', u'char_29', u'char_30', u'char_31', u'char_32',
       u'char_33', u'char_34', u'char_35', u'char_36', u'char_37', u'char_38'],
      dtype='object')

In [21]:
for cc in act2.columns:
    if act2[cc].dtype=='bool':
        act2[cc]=act2[cc]*1
    if "char" in cc:
        act2[cc]=act2[cc].fillna('type 0')

True

In [29]:
act

,people_id,activity_id,date,activity_category,char_1,char_2,char_3,char_4,char_5,char_6,char_7,char_8,char_9,char_10,outcome
0,ppl_100,act2_1734928,2023-08-26,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 76,0
1,ppl_100,act2_2434093,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
2,ppl_100,act2_3404049,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
3,ppl_100,act2_3651215,2023-08-04,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
4,ppl_100,act2_4109017,2023-08-26,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
5,ppl_100,act2_898576,2023-08-04,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1727,0
6,ppl_100002,act2_1233489,2022-11-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
7,ppl_100002,act2_1623405,2022-11-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
8,ppl_100003,act2_1111598,2023-02-07,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
9,ppl_100003,act2_1177453,2023-06-28,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
10,ppl_100003,act2_133509,2022-08-10,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 894,1
11,ppl_100003,act2_1408475,2023-03-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 143,1
12,ppl_100003,act2_1610829,2022-09-13,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
13,ppl_100003,act2_1688731,2023-02-10,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 297,1
14,ppl_100003,act2_1961720,2023-06-28,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 269,1
15,ppl_100003,act2_1988351,2022-08-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
16,ppl_100003,act2_2198176,2022-08-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
17,ppl_100003,act2_2437661,2023-02-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
18,ppl_100003,act2_2476911,2023-03-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
19,ppl_100003,act2_2557270,2022-08-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 230,1
20,ppl_100003,act2_2581989,2023-02-21,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
21,ppl_100003,act2_3116385,2023-02-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
22,ppl_100003,act2_3159712,2022-08-30,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
23,ppl_100003,act2_3292005,2023-05-03,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
24,ppl_100003,act2_3461867,2023-08-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
25,ppl_100003,act2_3468306,2023-03-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 143,1
26,ppl_100003,act2_3867292,2023-02-10,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
27,ppl_100003,act2_3990676,2023-08-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 276,1
28,ppl_100003,act2_4102292,2023-08-30,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
29,ppl_100003,act2_4160587,2023-02-21,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197261,ppl_99994,act2_2053669,2023-01-19,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197262,ppl_99994,act2_2053762,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 418,1
2197263,ppl_99994,act2_2134893,2023-08-23,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1396,1
2197264,ppl_99994,act2_2139237,2023-06-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197265,ppl_99994,act2_2233766,2023-06-28,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197266,ppl_99994,act2_2499779,2023-02-19,type 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 61,1
2197267,ppl_99994,act2_2514377,2023-06-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197268,ppl_99994,act2_2537795,2023-01-12,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197269,ppl_99994,act2_2582736,2023-06-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197270,ppl_99994,act2_2674371,2023-06-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197271,ppl_99994,act2_2808953,2023-05-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197272,ppl_99994,act2_2840212,2023-08-25,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 76,1
2197273,ppl_99994,act2_2992386,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 201,1
2197274,ppl_99994,act2_3177773,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 201,1
2197275,ppl_99994,act2_3284072,2023-07-14,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197276,ppl_99994,act2_3373847,2023-02-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197277,ppl_99994,act2_3534467,2023-08-17,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197278,ppl_99994,act2_3903321,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 418,1
2197279,ppl_99994,act2_4024188,2023-01-12,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 520,1
2197280,ppl_99994,act2_4355021,2023-02-23,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 602,1
2197281,ppl_99994,act2_4433480,2023-01-24,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197282,ppl_99994,act2_4440524,2023-08-17,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 759,1
2197283,ppl_99994,act2_4473896,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 418,1
2197284,ppl_99994,act2_4479985,2023-07-14,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 142,1
2197285,ppl_99994,act2_4581579,2023-01-13,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197286,ppl_99994,act2_4668076,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 418,1
2197287,ppl_99994,act2_4743548,2023-03-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1832,1
2197288,ppl_99994,act2_536973,2023-01-19,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1
2197289,ppl_99994,act2_688656,2023-05-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 199,1
2197290,ppl_99994,act2_715089,2023-06-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,1

In [28]:
p1=3/7.0
p2=4/7.0
-p1*np.log2(p1)-p2*np.log2(p2)

0.98522813603425152